name: anno
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.10.18
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libexpat=2.7.1
  - libffi=3.4.4
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywin32=311
  - pyzmq=27.0.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - altgraph==0.17.4
      - antspyx==0.6.1
      - astunparse==1.6.3
      - cachetools==6.2.4
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - diskcache==5.6.3
      - et-xmlfile==2.0.0
      - filelock==3.13.1
      - flatbuffers==25.12.19
      - fonttools==4.60.1
      - footsteps==0.1.9
      - fsspec==2025.10.0
      - gast==0.7.0
      - gdcm==1.1
      - girder-client==3.1.8
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - icon-registration==1.1.6
      - idna==3.4
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - itk==6.0b1.post1
      - itk-core==6.0b1.post1
      - itk-filtering==6.0b1.post1
      - itk-io==6.0b1.post1
      - itk-numerics==6.0b1.post1
      - itk-registration==6.0b1.post1
      - itk-segmentation==6.0b1.post1
      - jinja2==3.1.4
      - joblib==1.5.2
      - keras==2.15.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - multipledispatch==1.0.0
      - networkx==3.3
      - nibabel==5.3.2
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - pandas==2.3.1
      - patsy==1.0.2
      - peakutils==1.3.5
      - pefile==2023.2.7
      - pillow==11.0.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydicom==3.0.1
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pylibjpeg==2.1.0
      - pylibjpeg-libjpeg==2.1.0
      - pylibjpeg-openjpeg==2.5.0
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pytz==2025.2
      - pywin32-ctypes==0.2.3
      - pyyaml==6.0.3
      - qtrangeslider==0.1.5
      - requests==2.28.1
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - simpleitk==2.5.2
      - statsmodels==0.14.5
      - surfa==0.6.1
      - sympy==1.13.3
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.0.1+cpu
      - torchaudio==2.0.2+cpu
      - torchvision==0.15.2+cpu
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - unigradicon==1.0.4
      - urllib3==1.26.13
      - webcolors==24.11.1
      - werkzeug==3.1.4
      - wrapt==1.14.2
      - xxhash==3.6.0